# Generated by Django 5.2.5 on 2025-08-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Productos',
        ),
    ]
