# Generated by Django 5.2.5 on 2025-08-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_rename_project_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='created_at',
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productos',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productos',
            name='image',
            field=models.ImageField(upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
