# Generated by Django 5.2.5 on 2025-08-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_productos_created_at_productos_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productos',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
